# Generated by Django 3.2.8 on 2022-02-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Industry', models.TextField(max_length=50)),
                ('Activity_rate', models.FloatField(default='mercury inputs from the amount of mercury containing material fed into the system')),
                ('Input_factor', models.FloatField(default='general data on the mercury concentration in the feed material')),
                ('Output_distribution_factors', models.FloatField(default='mercury amount on the relevant release pathways based on available data')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Location', models.TextField(max_length=50)),
            ],
        ),
    ]
