# Generated by Django 3.2.8 on 2022-02-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_data',
        ),
    ]
