# Generated by Django 3.2.8 on 2022-02-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_user_user_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_data',
            new_name='userdata',
        ),
    ]
