# Generated by Django 4.0.1 on 2022-02-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_userdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='Part_A',
            field=models.TextField(default='1. Information on the party'),
        ),
    ]
